In [6]:
## Assignment 3 ##

In [7]:
## Task 1 ## 

## Question 1 ##

In [18]:
def compute(a,b):
    try:
        res = a/b
        return res
    except:
        print("ERROR")
compute(5,0)

ERROR


In [20]:
## Question 2 ##

In [31]:
def sentence(subjects , verbs , objects):
    k = 0
    for i in subjects:
        for j in objects:
            print(i + " " + verbs[k] + " " + j)
        for j in objects:
            print(i + " " + verbs[1] + " " + j)
        

subjects = ["Americans" , "Indians"]
verbs = ["plays" , "watch"]
objects = ["Baseball" , "cricket"]
sentence(subjects , verbs , objects)

Americans plays Baseball
Americans plays cricket
Americans watch Baseball
Americans watch cricket
Indians plays Baseball
Indians plays cricket
Indians watch Baseball
Indians watch cricket


In [27]:
## TASK 2 ##

In [28]:
## Question 1 ##

In [43]:
import numpy as np
def vander(ipvector, n, increasing=False):
    if not increasing:
        my_matrix = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        my_matrix = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return my_matrix

inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = vander(inputvector,no_col_opmat,False)
op_matx_inc_order = vander(inputvector,no_col_opmat,True)

print("matrix of the input array in dec. order of powers:\n\n",op_matx_dec_order,"\n")
print("matrix of the input array in inc. order of powers:\n\n",op_matx_inc_order,"\n")

inputvector = np.array([1,2,4,6,8,10])
no_col_opmat = 5
op_matx_dec_order = vander(inputvector,no_col_opmat,False)
op_matx_inc_order = vander(inputvector,no_col_opmat,True)
print("matrix of the input array in dec. order of powers:\n\n",op_matx_dec_order,"\n")
print("matrix of the input array in inc. order of powers:\n\n",op_matx_inc_order,"\n")


matrix of the input array in dec. order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

matrix of the input array in inc. order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

matrix of the input array in dec. order of powers:

 [[    1     1     1     1     1]
 [   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]] 

matrix of the input array in inc. order of powers:

 [[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [    1     8    64   512  4096]
 [    1    10   100  1000 10000]] 

